### ISSUE TITLE
Errors in Typescript Definition

### ISSUE THREAD

**Issue by SCasarotto** [Drazail/react-native-hash#18]
**Describe the bug**

When upgrading a project to typescript I found some inconsistency between the docs and the types.

1. It appears that `JSHash` is just a name space and thus you are unable to `JSHash(...)` but instead the types require `JSHash.hashString(...)`.
2. All of the `CONSTANTS.HashAlgorithms` are typed as `String` but `JSHash.hashString` is expecting `string` as its second argument.

**To Reproduce**
1. Create a typescript react native project
2. Attempt to use react-native-hash

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/13336976/99106982-c1249400-25aa-11eb-94a2-e76a7e6029a9.png)
![image](https://user-images.githubusercontent.com/13336976/99106960-b8cc5900-25aa-11eb-8732-6cb774f45b89.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version: [e.g. 1803]
 - React Native Version [e.g. Run `react-native info` in your terminal and copy the results here.]

**Smartphone (please complete the following information):**

**Additional context**

I am not 100% sure how the `JSHash` should be typed to fix this but I would be happy to submit a PR for the `String` to `string` fix.

**Comment by Drazail** [comment]
@SCasarotto 

feel free to make a PR

**Comment by SCasarotto** [comment]
No problem. Will test out a few ways to type it locally and submit a PR within the next week.

**Comment by Drazail** [comment]
@SCasarotto 

I've made some changes to type defs, please install the module from github (`npm install Drazail/react-native-hash#master`) and let me know if the issue is resolved so we can push an update to npm.

**Comment by SCasarotto** [comment]
Awesome. Taking a quick glance at those types, they look accurate.  I won't likely circle back to this until tomorrow or early next week but will verify them then though. Thanks!

**Comment by SCasarotto** [comment]
Based on my initial tests these new type definition files look great! Thanks!

**Comment by Drazail** [comment]
published on npm @ 1.3.1
