### ISSUE TITLE
Require Cycle Warning

### ISSUE THREAD

**Issue by riazufila** [Drazail/react-native-hash#29]
**Describe the bug**
A warning on require cycles.

**To Reproduce**
1. `import {JSHash, CONSTANTS} from 'react-native-hash';`
2. `JSHash("message", CONSTANTS.HashAlgorithms.sha256)
  .then(hash => console.log(hash))
  .catch(e => console.log(e));`

**Expected behavior**
No warning.

**Desktop (please complete the following information):**
 - OS: Linux
 - OS Version: Latest (Rolling Release)
 - React Native Version [e.g. Run `react-native info` in your terminal and copy the results here.]: 0.64.2

**Smartphone (please complete the following information):**
 - Device: Realme 6 Pro
 - OS: Android 10

**Additional context**
`Require cycle: node_modules/react-native-hash/JSHash/lib/core/WordArray.js -> node_modules/react-native-hash/JSHash/lib/core/Hex.js -> node_modules/react-native-hash/JSHash/lib/core/WordArray.js`

`Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.`

**Comment by Drazail** [comment]
The cyclic dependency you mentioned is a very old bug within the core module of this package I haven't got around fixing yet.

However, as the user space API has been developed with that in mind, you should not face any problems regarding uninitialized values.

Thanks for reminding me of this bug and I'll make sure to put this issue on top of my priority list.

**Comment by pardeshishubham** [comment]
am facing the same issue.
