### ISSUE TITLE
null is not an object

### ISSUE THREAD

**Issue by Franky238** [Drazail/react-native-hash#5]
**Describe the bug**
Cannot use RNHash.hashString because: null is not an object. Android is working but ios not.

**To Reproduce**
1. Import library
2. Try to use function as described.
3. Run ios

**Expected behavior**
I should not see an error on ios device

**Screenshots**
![image](https://user-images.githubusercontent.com/3315390/77850421-af84ac80-71d2-11ea-80a8-95c8cda5c7d7.png)

**Desktop (please complete the following information):**
 - OS: OSX 
 - OS Version: 10.15.3
 - React Native Version
```
 System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 40.24 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native: 0.61.5
```

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: latest

**Comment by Drazail** [comment]
@Franky238 
RNHash is only Implemented on Android.

You can use JSHash for cross platform purposes:

https://github.com/Drazail/react-native-hash/blob/master/README.md#other-platforms

**Comment by lostwood** [comment]
hi i have the same problem but android phone,
i was testing the example app, as you can see on the screenchots, but i got the error "null is not an object" 
![Screenshot_2020-05-12-10-53-53-146_host exp exponent](https://user-images.githubusercontent.com/16200298/81709061-a4fb3b00-943f-11ea-9ad1-08b4b13f54b5.jpg)
![Screenshot_2020-05-12-10-57-54-202_host exp exponent](https://user-images.githubusercontent.com/16200298/81709124-afb5d000-943f-11ea-80e9-614ea661e2fe.jpg)

**Comment by Drazail** [comment]
@lostwood 
Are you using expo?

**Comment by lostwood** [comment]
yes, i am using expo

**Comment by lostwood** [comment]
i installed the module inside the project then in the code
import RnHash, { CONSTANTS } from "react-native-hash";
but when i run console.log(RnHash) the result is null, so i think some configure is missing

**Comment by Drazail** [comment]
@lostwood 

expo doesn't support native modules. you either have to eject or use JSHash.

is the feature you are looking for absent in JSHash?

**Comment by lostwood** [comment]
I used RNHash because I need to generate hmac-sha256, now I just using react native with out expo, but the error persist, is there something I can do?

**Comment by Drazail** [comment]
@lostwood 
Implementing HMAC on JSHash is on the road map, ill try developing it asap.

as for testing:
It is almost definitely a problem with your initial setup as RNHash is being on tens of thousands of devices without any error reports.
try cloning the repo, cd into the example and do `$ npx react-native run-android`. if this works it means there is something wrong with your initial setup.

**Comment by Drazail** [comment]
@lostwood
Implementing HMAC on JSHash is on the road map, ill try developing it asap.

as for testing:
there is probably a problem with your initial setup as RNHash is being used on tens of thousands of devices without any error reports. 
however there can always be an oversight on my end, to test it please try cloning the repo, cd into the example and do `$ npx react-native run-android`. if this works it means there is something wrong with your initial setup, otherwise, please share the logs with me, so I can investigate further.

**Comment by lostwood** [comment]
i downloaded the repo, and i did what you told me, and this was the output


![error](https://user-images.githubusercontent.com/16200298/82129367-2fb99e00-9790-11ea-901b-cae2307f635c.png)

**Comment by lostwood** [comment]
after running on a real devices the function works

**Comment by Drazail** [comment]
@lostwood 

then that probably has something to do with the initial expo configuration.

as of [this](https://github.com/Drazail/react-native-hash/commit/db2241ad1d52ac2ac7a955bdcb412a05cf6d42bb) commit  (release [1.3.0](https://github.com/Drazail/react-native-hash/releases/tag/1.3.0)) you can use JSHmac to generate HMAC from the JS side of things, ie:

```
import {  JSHmac, CONSTANTS } from "react-native-hash";

JSHmac("message", "SecretKey", CONSTANTS.HmacAlgorithms.HmacSHA256)
  .then(hmac=> console.log(hmac))
  .catch(e => console.log(e));
```

this should work with all expo workflows as well.
