### ISSUE TITLE
CONSTANTS's HashAlgorithms is not correct.

### ISSUE THREAD

**Issue by Tony---Zhang** [Drazail/react-native-hash#6]
**Describe the bug**
The values in CONSTANTS is not corrected, I tried `HashAlgorithms.sha256`, but the correct value should be `sha256` rather than `'SHA-256'`
const CONSTANTS = {
  HashAlgorithms: {
    md2: 'MD2',
    md5: 'MD5',
    sha1: 'SHA-1',
    sha224: 'SHA-224',
    sha256: 'SHA-256',
    sha384: 'SHA-384',
    sha512: 'SHA-512',
    keccak: 'keccak',
  }

**Comment by Drazail** [comment]
@Tony---Zhang 

yep, seems like after changing some Android APIs I forgot to adjust JSHash to new constants.

Should be fixed now: 
* Commit fc8106a 
* release 1.2.6

**Comment by Tony---Zhang** [comment]
@Drazail 
It's better to update README also, thanks a lot
