### ISSUE TITLE
Incorrect React Native Version

### ISSUE THREAD

**Issue by jacksob1** [Drazail/react-native-hash#70]
**Describe the bug**
This issue was noted before in a previous issue but seemed to be ignored because they didn't fill out the issue in the format you wanted. The peer dependency and dev dependency requirements is ^0.7 instead of ^0.70 which is causing the SymVer check to fail.

**To Reproduce**
1. Tried to run npm install while using react native 0.70.1

**Expected behavior**
I would've expected all of the packages to be installed correctly, but I get an npm error saying that it is unable to resolve the react native dependency for this package since it expected version ^0.7, but only found 0.70.1.

**Screenshots**
![image](https://user-images.githubusercontent.com/64814338/191585770-675562e1-8521-4ab1-8607-e61af5f18712.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: 20H2
 - React Native Version: 0.70.1

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: Android 12

**Additional context**
The previous issue: [https://github.com/Drazail/react-native-hash/issues/68]

**Comment by Drazail** [comment]
@jacksob1 please install the package from GitHub (`npm install Drazail/react-native-hash#master`) and let me know the result.

**Comment by jacksob1** [comment]
@Drazail that allowed me to install it.

**Comment by Drazail** [comment]
3.0.3 published on npm, please install the package from npm (`npm install react-native-has`) and let me know the result.

problem seems to be originating from conflicts between `testing-library` and `react-native`. 

I removed the dependency for now and will add it back in when `testing-library` manages to resolve said conflicts. Meanwhile to run the tests, you will have to install `testing-library` and resolve the conflicts manually.
