### ISSUE TITLE
[TypeError: null is not an object (evaluating '_reactNativeHash.default.generateHmac')]

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [Drazail/react-native-hash#72]
**Describe the bug**
[TypeError: null is not an object (evaluating '_reactNativeHash.default.generateHmac')]

 - OS: ios - emulator
 - OS Version: ios
 - React Native : 67.4

**Smartphone (please complete the following information):**
 - Device: Emulator

**Additional context**

**Comment by Drazail** [comment]
`generateHmac` is not implemented for iOS, please use `JSHmac` instead:

```
import { JSHmac, CONSTANTS } from "react-native-hash";

JSHmac("message", "SecretKey", CONSTANTS.HmacAlgorithms.HmacSHA256)
  .then(hash => console.log(hash))
  .catch(e => console.log(e));
```
