### ISSUE TITLE
Comparing hashes with string?

### ISSUE THREAD

**Issue by johhansantana** [Drazail/react-native-hash#74]
Pardon my ignorance on this topic and I apologize if this is not the place to ask but I was wondering if there's a way to compare a regular string with a hashed one using this library?

**Comment by Drazail** [comment]
The hash functions return a string by default, so a simple `===` check should do the job.
For instance: 
`jsHash(unHashedString, CONSTANTS.HashAlgorithms.sha256) === hashedString`

If you need the raw bits or require a different encoding, you can use packages like [js-encoding-utils](https://www.npmjs.com/package/js-encoding-utils).
